import { Component, OnInit } from "@angular/core";
import { Staff } from "src/app/models/staff-interface";

@Component({
  selector: "app-staff",
  templateUrl: "./staff.page.html",
  styleUrls: ["./staff.page.scss"],
})
export class StaffPage implements OnInit {
  staffs = StaffMembers;

  constructor() {}

  ngOnInit() {
    console.log("user", this.staffs);
  }
}

var StaffMembers: Staff[] = [
  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 100,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },
  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },
  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },
  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },
  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },
  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },
  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },
  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },
  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },

  {
    staffName: "John Doe",
    paid: 400,
    earned: 100,
    projects: 7,
    toPay: 100,
    paidOn: new Date(),
    orderDetails: [
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
      {
        projectName: "React Project",
        deliveryDate: new Date(),
        earning: 0,
        expense: 400,
        status: "pending",
        paidOn: new Date(),
      },
    ],
  },
];
